# Generated by Django 4.2.4 on 2023-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
