# Generated by Django 4.2.4 on 2023-09-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subcategory',
            new_name='age',
        ),
    ]
