# Generated by Django 4.2.4 on 2023-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_subcategory_question_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='answers',
        ),
        migrations.AddField(
            model_name='folder',
            name='questions',
            field=models.ManyToManyField(related_name='folders', to='api.question'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
