# Generated by Django 4.2.4 on 2023-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_folder_answers_folder_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='folders', to='api.question'),
        ),
    ]
