# Generated by Django 4.2.4 on 2023-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='folders',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='api.folder'),
        ),
    ]
