# Generated by Django 4.2.4 on 2023-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_folder_questions_question_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='questions', to='api.folder'),
        ),
    ]
