# Generated by Django 4.2.4 on 2023-09-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_folder_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'user')},
        ),
    ]
