# Generated by Django 4.2.4 on 2023-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_answer_text1_answer_text2_answer_text3_answer_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
