# Generated by Django 4.2.4 on 2023-10-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_answer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
