# Generated by Django 4.2.4 on 2023-10-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_refreshtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
